# Generated by Django 5.2 on 2025-04-08 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainervehicle',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignments', to='vehicles.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='trainerschedule',
            unique_together={('trainer', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
