# Generated by Django 5.2 on 2025-04-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(choices=[('CAR', 'Car'), ('SCOOTY', 'Scooty'), ('BOTH', 'Both Car and Scooty'), ('HEAVY', 'HEAVY'), ('OTHER', 'Other')], default='BOTH', max_length=10),
        ),
    ]
